trainer:
  accelerator: auto
  default_root_dir: 'runs/causal_v2/'
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/loss
        mode: min
        save_last: true
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/loss
        patience: 10
        mode: min
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
  log_every_n_steps: 1
  max_epochs: 80

data:
  class_path: data.LitDataModule
  init_args:
    time: 1381528818 
    kernel: 60.0
    stride: 1.0
    causal: True
    batch_size: 32
    num_workers: 4

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-3

lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.75
    
model:
  class_path: model.LitModel
  init_args:
    d_input: &d_input 9
    d_output: &d_output 4
    encoder:
        class_path: models.networks.S4DModel
        init_args: 
           d_input: *d_input
           d_output: *d_output
           d_model: 64
           n_layers: 8
           dropout: 0.0
           prenorm: False
           maxpool: True
