trainer:
  accelerator: auto
  default_root_dir: 'runs/test/'
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/loss
        mode: min
        save_last: true
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/loss
        patience: 5
        mode: min
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
  log_every_n_steps: 1
  max_epochs: 80

data:
  class_path: data.LitDataModule
  init_args:
    time: 1381528818 
    kernel: 60.0
    stride: 1.0
    batch_size: 32
    num_workers: 1

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-2

lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.99
    
model:
  class_path: model.LitModel
  init_args:
    d_input: &d_input 9
    d_output: &d_output 1
    encoder:
        class_path: models.networks.DeepClean
        init_args: 
           in_channels: *d_input
